id: P010787
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W8LS18883
  title: ཐོན་རྫས་ཀྱི་སྤུས་ཀའི་སྐོར་གྱི་ཀྲུང་ཧྭ་མི་དམངས་སྤྱི་མཐུན་རྒྱལ་ཁབ་ཀྱི་བཅའ་ཁྲིམས།
  author: ''
  volumes:
    becc5be24fb64ea0a38f3c1f940f5097:
      image_group_id: I8LS18885
      title: ''
      volume_number: 1
      total_pages: 54
      base_file: v001.txt
